/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProductStatus = "active" | "archived" | "draft";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Products {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  images: Json | null;
  name: string;
  organizationId: string;
  slug: string;
  status: Generated<ProductStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Variants {
  basePrice: Generated<Numeric>;
  costPrice: Numeric | null;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  currency: Generated<string>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  images: Json | null;
  isDefault: Generated<boolean>;
  name: string;
  productId: string;
  salePrice: Numeric | null;
  sku: string;
  status: Generated<ProductStatus>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  products: Products;
  session: Session;
  user: User;
  variants: Variants;
  verification: Verification;
}
